/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.25.84
  from /Users/Shared/projects/git/frege-data-science/src/main/frege/ch/fhnw/thga/datascience/HelloWorld.fr
  Do not edit this file! Instead, edit the source file and recompile.
*/

package ch.fhnw.thga.datascience;

import frege.run8.Func;
import frege.run8.Lazy;
import frege.run8.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Semigroupoid;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeDecimal;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="/Users/Shared/projects/git/frege-data-science/src/main/frege/ch/fhnw/thga/datascience/HelloWorld.fr",
  time=1634118700418L, jmajor=16, jminor=-1,
  imps={
    "frege.Prelude", "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase", "frege.prelude.PreludeDecimal",
    "frege.prelude.PreludeIO", "frege.prelude.PreludeList", "frege.prelude.PreludeMonad", "frege.prelude.PreludeText",
    "frege.java.util.Regex"
  },
  nmss={
    "Prelude", "PreludeArrays", "PreludeBase", "PreludeDecimal", "PreludeIO", "PreludeList", "PreludeMonad",
    "PreludeText", "Regexp"
  },
  symas={}, symcs={}, symis={}, symts={},
  symvs={
    @Meta.SymV(
      offset=76, name=@Meta.QName(pack="ch.fhnw.thga.datascience.HelloWorld", base="sum"), stri="s(u)",
      sig=1, depth=1, rkind=13, doc=" add one to any number   "
    ),
    @Meta.SymV(
      offset=114, name=@Meta.QName(pack="ch.fhnw.thga.datascience.HelloWorld", base="main"), stri="u",
      sig=2, depth=0, rkind=8
    )
  },
  symls={},
  taus={
    @Meta.Tau(kind=9), @Meta.Tau(suba=0, tvar="a"),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="ST")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="RealWorld")}),
    @Meta.Tau(kind=0, suba=2, subb=3),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="()")}),
    @Meta.Tau(kind=0, suba=4, subb=5)
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=1),
    @Meta.Rho(
      cont={@Meta.Context(clas=@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Num"), tau=1)}, sigma=0,
      rhotau=0
    ),
    @Meta.Rho(rhofun=false, rhotau=6)
  },
  sigmas={@Meta.Sigma(rho=0), @Meta.Sigma(bound={"a"}, kinds={0}, rho=1), @Meta.Sigma(rho=2)}, exprs={@Meta.Expr()}
)
final public class HelloWorld  {
  




final public static <𝓐> 𝓐 sum(final PreludeBase.CNum<𝓐> ctx$1, final Lazy<𝓐> arg$1) {
  return ctx$1.ƒ$plus(arg$1, Thunk.<𝓐>shared((Lazy<𝓐>)(() -> ctx$1.ƒfromInt(Thunk.<Integer>lazy(1)))));
}
final public static Lazy<Func.U<RealWorld, Short>> $main = Thunk.<Func.U<RealWorld, Short>>shared(
      (Lazy<Func.U<RealWorld, Short>>)(() -> {
            return Prelude.putStrLn("Hello World");
          })
    );

  public static void main(final java.lang.String[] argv) {
    try {
      frege.run.RunTM.argv = argv;
      
        PreludeBase.TST.<Short>performUnsafe($main
               .call()
          ).call();
      frege.runtime.Runtime.stdout.get().close();
      frege.runtime.Runtime.stderr.get().close();

    } finally { frege.run.Concurrent.shutDownIfExists(); }
  }
}
